///////////////////////////////////////////////////////////
//  GameScene.cs
//  Implementation of the Class GameScene
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:49
//  Original author: Ralf
///////////////////////////////////////////////////////////

using Components;
using Entitys;
using System.Collections.Generic;
using System.Drawing;
using ToBeDecided.Components.Behaviours;
using ToBeDecided.Entitys;
using ToBeDecided.MapClasses;
using WaveEngine.Components.Cameras;
using WaveEngine.Framework;
using WaveEngine.Framework.Physics2D;

namespace ToBeDecided.Scenes
{
    public class GameScene : Scene {

		public GameSceneBehaviour gameSceneBehaviour { get; private set; }
        public List<GameObject> gameObjects { get; private set; }
        private Map map;
        public Player player { get; set; }


		public GameScene(){

		}

		/// <param name="map">Die Map, die für diese Scene verwendet werden soll</param>
		/// <param name="player">Der Player, der für diese Scene verwendet werden soll</param>
		public GameScene(Map map){
            this.map = map;

            gameSceneBehaviour = new GameSceneBehaviour();

            //Noch nicht sicher, ob "PostUpdate" oder "PreUpdate" besser für uns ist
            AddSceneBehavior(gameSceneBehaviour, SceneBehavior.Order.PostUpdate);
            gameObjects = new List<GameObject>();

		}

        protected override void CreateScene()
        {
            //throw new NotImplementedException();
            FixedCamera2D camera = new FixedCamera2D("Camera");
            camera.Entity.AddComponent(new CameraTrackBehaviour(player, new Rectangle(0, 0, map.getWidth(), map.getHeight())));
            EntityManager.Add(camera);

            EntityManager.Add(map);
            EntityManager.Add(player);

        }

        public bool isFree(Collider2D collider)
        {
            if (map.requestMovement(collider.Transform2D) == false)
                return false;
            foreach (GameObject gameObject in gameObjects)
            {
                if (collider.Intersects(gameObject.collider))
                    return false;
            }

            return true;
        }

        public void addGameObject()
        {

        }

        public void addWeapon(Weapon weapon)
        {

        }

    }//end GameScene

}//end namespace Scenes