///////////////////////////////////////////////////////////
//  GameScene.cs
//  Implementation of the Class GameScene
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:49
//  Original author: Ralf
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Components;
using Entitys;
using Map;
namespace Scenes {
	public class GameScene {

		public Components.GameSceneBehaviour m_GameSceneBehaviour;



		~GameScene(){

		}

		public GameScene(){

		}

		/// 
		/// <param name="map"></param>
		/// <param name="player">player</param>
		public GameScene(Map map, Player player){

		}

		public void finalize(){

		}

	}//end GameScene

}//end namespace Scenes