///////////////////////////////////////////////////////////
//  GameScene.cs
//  Implementation of the Class GameScene
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:49
//  Original author: Ralf
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Components;
using Entitys;
using MapClasses;
using WaveEngine.Framework;
using WaveEngine.Framework.Graphics;
using WaveEngine.Components.Cameras;

namespace Scenes {
	public class GameScene : Scene {

		public GameSceneBehaviour gameSceneBehaviour;


		public GameScene(){

		}

		/// <param name="map"></param>
		/// <param name="player">player</param>
		public GameScene(Map map, Player player){

		}

        protected override void CreateScene()
        {
            //throw new NotImplementedException();
            EntityManager.Add(new FixedCamera2D("Camera"));
        }

    }//end GameScene

}//end namespace Scenes