///////////////////////////////////////////////////////////
//  TitleScene.cs
//  Implementation of the Class TitleScene
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:51
//  Original author: Ralf
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Scenes {
	public class TitleScene {



		~TitleScene(){

		}

		public TitleScene(){

		}

		public void finalize(){

		}

	}//end TitleScene

}//end namespace Scenes