///////////////////////////////////////////////////////////
//  TitleScene.cs
//  Implementation of the Class TitleScene
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:51
//  Original author: Ralf
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using WaveEngine.Framework;

namespace Scenes {
	public class TitleScene : Scene {

		public TitleScene(){

		}

        protected override void CreateScene()
        {
            throw new NotImplementedException();
        }
    }//end TitleScene

}//end namespace Scenes