///////////////////////////////////////////////////////////
//  Map.cs
//  Implementation of the Class Map
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:49
//  Original author: Ralf Keller
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Scenes;
using SpawnerClasses;
using WaveEngine.Common.Math;
using TiledSharp;

namespace MapClasses {
	public class Map {

		public GameScene gameScene;
        private TmxMap tmxMap;

		public Map(TmxMap tmxMap) {
            this.tmxMap = tmxMap;
		}

		/// <param name="schwierigkeit">schwierigkeit</param>
		public List<Spawner> getSpawner(int schwierigkeit){
            return null;
		}

		/// 
		/// <param name="rectangle">rectangle</param>
		public bool requestMovement(Rectangle rectangle){

			return false;
		}

	}//end Map

}//end namespace Map