///////////////////////////////////////////////////////////
//  MapLoader.cs
//  Implementation of the Class MapLoader
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:50
//  Original author: Ralf Keller
///////////////////////////////////////////////////////////

using System;
using TiledSharp;

namespace MapClasses {
	public class MapLoader {

        //public Map m_Map;
        private static MapLoader instance;

		private MapLoader(){

		}

		public void finalize(){

		}

		public static MapLoader getInstance(){
            if (instance == null)
                instance = new MapLoader();
            return instance;
		}

		/// 
		/// <param name="path">path</param>
		public Map load(String path){
            TmxMap tmxMap = new TmxMap(path);

            Map map = new Map(tmxMap);
            return map;
		}

	}//end MapLoader

}//end namespace Map