///////////////////////////////////////////////////////////
//  MapLoader.cs
//  Implementation of the Class MapLoader
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:50
//  Original author: Ralf Keller
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using MapClasses;
namespace MapClasses {
	public class MapLoader {

		public Map m_Map;



		~MapLoader(){

		}

		public MapLoader(){

		}

		public void finalize(){

		}

		public static MapLoader getInstance(){

			return null;
		}

		/// 
		/// <param name="path">path</param>
		public Map load(String path){

			return null;
		}

	}//end MapLoader

}//end namespace Map