///////////////////////////////////////////////////////////
//  EnemyBehaviour.cs
//  Implementation of the Interface EnemyBehaviour
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:48
//  Original author: Ralf
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Components {
	public interface EnemyBehaviour  {

	}//end EnemyBehaviour

}//end namespace Components