///////////////////////////////////////////////////////////
//  GameSceneBehaviour.cs
//  Implementation of the Class GameSceneBehaviour
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:49
//  Original author: Ralf Keller
///////////////////////////////////////////////////////////

using Entitys;
using System;
using System.Collections.Generic;
using ToBeDecided.Entitys;
using ToBeDecided.MapClasses;
using WaveEngine.Framework;

namespace ToBeDecided.Components.Behaviours
{
    public class GameSceneBehaviour : SceneBehavior {

        private Player player;
        private List<GameObject> gameObjects;
        private Map map;

		public GameSceneBehaviour(){

		}

		public GameSceneBehaviour(List<GameObject> gameObjects, Map map){
            this.gameObjects = gameObjects;
            this.map = map;
		}

        protected override void ResolveDependencies()
        {
            player = Scene.EntityManager.Find<Player>("Player");
        }

        protected override void Update(TimeSpan gameTime)
        {
            //throw new NotImplementedException();
        }
    }//end GameSceneBehaviour

}//end namespace Components