///////////////////////////////////////////////////////////
//  GameSceneBehaviour.cs
//  Implementation of the Class GameSceneBehaviour
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:49
//  Original author: Ralf Keller
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Components {
	public class GameSceneBehaviour {

		public GameSceneBehaviour(){

		}

		~GameSceneBehaviour(){

		}

		/// 
		/// <param name="gameObjects"></param>
		/// <param name="map"></param>
		public GameSceneBehaviour(List<GameObject> gameObjects, Map map){

		}

	}//end GameSceneBehaviour

}//end namespace Components