///////////////////////////////////////////////////////////
//  GameSceneBehaviour.cs
//  Implementation of the Class GameSceneBehaviour
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:49
//  Original author: Ralf Keller
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using WaveEngine.Framework;
using Entitys;
using MapClasses;

namespace Components {
	public class GameSceneBehaviour : Behavior {

		public GameSceneBehaviour(){

		}

		public GameSceneBehaviour(List<GameObject> gameObjects, Map map){

		}

        protected override void Update(TimeSpan gameTime)
        {
            throw new NotImplementedException();
        }
    }//end GameSceneBehaviour

}//end namespace Components