///////////////////////////////////////////////////////////
//  InputController.cs
//  Implementation of the Interface InputController
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:49
//  Original author: Ralf
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Components {
	public interface InputController  {

	}//end InputController

}//end namespace Components