///////////////////////////////////////////////////////////
//  MenuInputController.cs
//  Implementation of the Class MenuInputController
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:50
//  Original author: Ralf
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Components;
namespace Components {
	public class MenuInputController : InputController {

		public MenuInputController(){

		}

		~MenuInputController(){

		}

	}//end MenuInputController

}//end namespace Components