///////////////////////////////////////////////////////////
//  PlayerBehaviourComponent.cs
//  Implementation of the Class PlayerBehaviourComponent
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:51
//  Original author: Ralf
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Components {
	public class PlayerBehaviourComponent {



		~PlayerBehaviourComponent(){

		}

		public PlayerBehaviourComponent(){

		}

		public void finalize(){

		}

	}//end PlayerBehaviourComponent

}//end namespace Components