///////////////////////////////////////////////////////////
//  StatComponent.cs
//  Implementation of the Class StatComponent
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:51
//  Original author: Ralf
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using WaveEngine.Framework;

namespace Components {
	public class StatComponent : Component {

		private int currentHealth;
		private int maxHealth;
		private int speed;
		private int strength;

		public StatComponent(){

		}

	}//end StatComponent

}//end namespace Components