///////////////////////////////////////////////////////////
//  Weapon.cs
//  Implementation of the Interface Weapon
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:52
//  Original author: Ralf
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Components {
	public interface Weapon  {

	}//end Weapon

}//end namespace Components