///////////////////////////////////////////////////////////
//  GameHandler.cs
//  Implementation of the Class GameHandler
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:48
//  Original author: Ralf
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Entitys;
public class GameHandler {

	public GameHandler(){

	}

	/// 
	/// <param name="enemy">enemy</param>
	public void announceDeath(IEnemy enemy){

	}

	public static GameHandler getInstance(){

		return null;
	}

}//end GameHandler