///////////////////////////////////////////////////////////
//  MapChangeTrigger.cs
//  Implementation of the Class MapChangeTrigger
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:50
//  Original author: Ralf Keller
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class MapChangeTrigger {

	private string nextMap;

	public MapChangeTrigger(){

	}

	~MapChangeTrigger(){

	}

}//end MapChangeTrigger