//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 19.06.2016 12:28:05
namespace ToBeDecided
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/desert.tmx </summary>
            public const string desert_tmx = "Content/Assets/desert.tmx";
            
            /// <summary> Path to Content/Assets/desert.tsx </summary>
            public const string desert_tsx = "Content/Assets/desert.tsx";
            
            /// <summary> Path to Content/Assets/TitleBackground.jpg </summary>
            public const string TitleBackground_jpg = "Content/Assets/TitleBackground.jpg";
            
            /// <summary> Path to Content/Assets/tmw_desert_spacing.png </summary>
            public const string tmw_desert_spacing_png = "Content/Assets/tmw_desert_spacing.png";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
