///////////////////////////////////////////////////////////
//  IAction.cs
//  Implementation of the Interface IAction
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:49
//  Original author: Ralf Keller
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Actions {
	public interface IAction  {

		/// 
		/// <param name="gameScene"></param>
		void execute(GameScene gameScene);
	}//end IAction

}//end namespace Actions