///////////////////////////////////////////////////////////
//  MovementAction.cs
//  Implementation of the Class MovementAction
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:50
//  Original author: Ralf Keller
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Actions;
using Entitys;
using Scenes;

namespace Actions {
	public class MovementAction : IAction {

		public MovementAction(){

		}

		/// 
		/// <param name="gameObject"></param>
		public MovementAction(GameObject gameObject){

		}

        public void execute(GameScene gameScene)
        {
            throw new NotImplementedException();
        }

	}//end MovementAction

}//end namespace Actions