///////////////////////////////////////////////////////////
//  MovementAction.cs
//  Implementation of the Class MovementAction
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:50
//  Original author: Ralf Keller
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Actions;
namespace Actions {
	public class MovementAction : IAction {

		public MovementAction(){

		}

		~MovementAction(){

		}

		/// 
		/// <param name="gameObject"></param>
		public MovementAction(GameObject gameObject){

		}

		/// 
		/// <param name="gameScene"></param>
		public void execute(GameScene gameScene){

		}

	}//end MovementAction

}//end namespace Actions