///////////////////////////////////////////////////////////
//  Ork.cs
//  Implementation of the Class Ork
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:50
//  Original author: Ralf Keller
///////////////////////////////////////////////////////////

namespace ToBeDecided.Entitys.Enemies {
	public class Ork : Enemy {

		public Ork(){

		}

		~Ork(){

		}

	}//end Ork

}//end namespace Entitys