///////////////////////////////////////////////////////////
//  Enemy.cs
//  Implementation of the Class Enemy
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:48
//  Original author: Ralf
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Components;
using WaveEngine.Framework;
using Entitys;
namespace Entitys {
	public abstract class Enemy : GameObject, IEnemy {

        private StatComponent statComponent;

		public Enemy(){
            thisEntity = new Entity();
            thisEntity.AddComponent(statComponent);
		}

		public Enemy(StatComponent statComponent){

		}

		public void finalize(){

		}

	}//end Enemy

}//end namespace Entitys