///////////////////////////////////////////////////////////
//  Enemy.cs
//  Implementation of the Class Enemy
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:48
//  Original author: Ralf
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Components;
using Entitys;
namespace Entitys {
	public class Enemy : Gameobject, Gameobject {

		public Components.GameComponent m_GameComponent;
		public Components.StatComponent m_StatComponent;



		~Enemy(){

		}

		public Enemy(){

		}

		/// 
		/// <param name="statComponent">statComponent</param>
		public Enemy(StatComponent statComponent){

		}

		public void finalize(){

		}

	}//end Enemy

}//end namespace Entitys