///////////////////////////////////////////////////////////
//  Gameobject.cs
//  Implementation of the Class Gameobject
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:49
//  Original author: Ralf Keller
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Entitys {
	public class Gameobject {

		private Queue eventQueue;
		private GameScene gameScene;
		private bool isAlive;
		public event onDeath;

		public Gameobject(){

		}

		~Gameobject(){

		}

		public IAction getNextAction(){

			return null;
		}

		public bool isAlive(){

			return false;
		}

		private void onDeath(){

		}

		/// 
		/// <param name="damage"></param>
		public void recieveDamange(float damage){

		}

	}//end Gameobject

}//end namespace Entitys