///////////////////////////////////////////////////////////
//  Gameobject.cs
//  Implementation of the Class Gameobject
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:49
//  Original author: Ralf Keller
///////////////////////////////////////////////////////////

using Components;
using ToBeDecided.Components;
using ToBeDecided.Scenes;
using WaveEngine.Framework;
using WaveEngine.Framework.Graphics;
using WaveEngine.Framework.Physics2D;

namespace ToBeDecided.Entitys
{
    public class GameObject : BaseDecorator {

		protected GameScene gameScene;

        public StatComponent stats { get; protected set; }
        public Collider2D collider { get; protected set; }
        public Transform2D transform { get; protected set; }

        public bool isAlive
        {
            get; private set;
        }

        public delegate void OnDeathHandler();
		public event OnDeathHandler onDeathEvent;

		public GameObject(){
		}


		private void onDeath(){

		}
        
		public void recieveDamange(float damage){

		}

        protected void attack(Weapon weapon)
        {
            
        }
	}
}