///////////////////////////////////////////////////////////
//  IEnemy.cs
//  Implementation of the Interface IEnemy
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:49
//  Original author: Ralf Keller
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Entitys {
	public interface IEnemy  {

	}//end IEnemy

}//end namespace Entitys