///////////////////////////////////////////////////////////
//  Player.cs
//  Implementation of the Class Player
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:51
//  Original author: Ralf Keller
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using WaveEngine.Framework;

using Components;

namespace Entitys {
	public class Player : GameObject {

		//public Components.GameComponent m_GameComponent;
		public PlayerBehaviourComponent playerBehaviourComponent;
		public StatComponent statComponent;

		public Player(){
            thisEntity = new Entity();
		}

	}//end Player

}//end namespace Entitys