///////////////////////////////////////////////////////////
//  Player.cs
//  Implementation of the Class Player
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:51
//  Original author: Ralf Keller
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using WaveEngine.Framework;

using Components;
using WaveEngine.Framework.Graphics;
using WaveEngine.Framework.Physics2D;

namespace Entitys {
	public class Player : GameObject {

		public PlayerBehaviourComponent playerBehaviourComponent { get; private set; }
        public StatComponent statComponent { get; private set; }

		public Player(){
            playerBehaviourComponent = new PlayerBehaviourComponent(gameScene);
            collider = new RectangleCollider2D();
            statComponent = new StatComponent();

            Entity = new Entity("Player")
                .AddComponent(new Transform2D())
                .AddComponent(collider)
                .AddComponent(playerBehaviourComponent)
                .AddComponent(statComponent);
		}

	}//end Player

}//end namespace Entitys