///////////////////////////////////////////////////////////
//  Weapon.cs
//  Implementation of the Interface Weapon
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:52
//  Original author: Ralf
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using WaveEngine.Framework;
using ToBeDecided.Components;
using WaveEngine.Framework.Graphics;
using WaveEngine.Framework.Physics2D;

namespace Components {
	public abstract class Weapon : BaseDecorator {

        public Transform2D transform { get; protected set; }
        public Collider2D collider { get; protected set; }
        public WeaponStatComponent stats { get; protected set; }

	}//end Weapon

}//end namespace Components