///////////////////////////////////////////////////////////
//  Spawner.cs
//  Implementation of the Interface Spawner
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:51
//  Original author: Ralf
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Entitys;
using MapClasses;

namespace SpawnerClasses {
	public class Spawner  {

		IEnemy getType()
        {
            return null;
        }

		bool isTypeOf<E>()
        {
            return false;
        }

		/// 
		/// <param name="anzahl"></param>
		/// <param name="level"></param>
		void setBase<E>(int anzahl, int level)
        {
            
        }

		/// 
		/// <param name="map"></param>
		void setMap(Map map)
        {

        }

		void setType<E>()
        {

        }

		void spawn()
        {

        }
	}//end Spawner

}//end namespace Spawner