///////////////////////////////////////////////////////////
//  Spawner.cs
//  Implementation of the Interface Spawner
//  Generated by Enterprise Architect
//  Created on:      08-Jun-2016 18:24:51
//  Original author: Ralf
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Entitys;
using MapClasses;

namespace SpawnerClasses {
	public class Spawner  {

		public IEnemy getType()
        {
            return null;
        }

		public bool isTypeOf<E>()
        {
            return false;
        }

        /// 
        /// <param name="anzahl"></param>
        /// <param name="level"></param>
        public void setBase<E>(int anzahl, int level)
        {
            
        }

        /// 
        /// <param name="map"></param>
        public void setMap(Map map)
        {

        }

        public void setCount(int count)
        {

        }

        public void setLevel(int level)
        {

        }

        public void setType(Type t)
        {

        }

        public void spawn()
        {

        }
	}//end Spawner

}//end namespace Spawner